name: Build My Application
on: push

jobs:
  build:
    name: Build our App
    runs-on: ubuntu
    steps:
      - name: Hello World
        uses: actions/hello-world-javascript@v1
        with:
          who-to-greet: 'Mona the '
          id: hello

      - name: Print Current Directory
        run: pwd

      - name: List file in Directory
        run: ls
